### ISSUE TITLE
[BUG] error displayed on Workspace/Gallery page after logging in on a fresh setup

### ISSUE THREAD

**Issue by mKowalski256** [rspace-os/rspace-docker#1]
**Describe the bug**

I followed the documented setup for installing fresh [RSpace 2.0.0 release](https://github.com/rspace-os/rspace-web/releases/tag/2.0.0). Tomcat started fine, and I can see RSpace login page. Still, after logging in as a `sysadmin1` I don't see my Workspace, but rather an error saying `Database exception - query could not be executed`.

Note that I can browse some pages fine, e.g. I can open and use 'Inventory' tab fine.

**To Reproduce**
1. Start fresh install with [RSpace 2.0.0 release](https://github.com/rspace-os/rspace-web/releases/tag/2.0.0) .war file
2. Go to RSpace /login page, login as sysadmin1 (default password)
3. See an error page
4. After checking the server logs, see the `SQLGrammarException: could not execute statement` error 
(see attached: [error_log_excerpt.txt](https://github.com/user-attachments/files/16026709/login_error.txt))

**Expected behavior**
I should see RSpace Workspace, rather than an error.

**Screenshots**
![image](https://github.com/rspace-os/rspace-docker/assets/8066659/59068471-6689-4f38-a3ad-4589cb27c016)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Comment by mKowalski256** [comment]
This was due to one db column missing from both SQL initialization template, and also from liquibase updates that run during RSpace startup. I fixed the issue by adding to [db-template.sql](https://github.com/rspace-os/rspace-docker/blob/main/templates/db-template.sql) ([commit d838584](https://github.com/rspace-os/rspace-docker/commit/d838584611ccbd648eb69c3071d55df8bf715aaf)). 

@tuxRamon can you confirm that latest works fine?

**Comment by mKowalski256** [comment]
Also corrected in db initialization scripts provided within [rspace-web](https://github.com/rspace-os/rspace-web/commit/5972614ebd0c4c8d56f79328844693da9646596b) project.

**Comment by tuxRamon** [comment]
Tested on a fresh setup with updated db-template file and the issue was no longer encountered. Marking as closed.
