### ISSUE TITLE
[BUG]  Failed to save workspace settings could not complete: Status: 500 after 1st login

### ISSUE THREAD

**Issue by Tarydium** [rspace-os/rspace-docker#4]
After installing dokcer instance in a test local server i  got this error every time i login or load main page.
Failed to save workspace settings could not complete:
Status: 500 - server error
There was an error responding to this request, which has been logged.

Something went wrong: Request can't be processed - incorrect Origin/Referer headers:mismatched origin 'http://192.168.1.10:8095'

Ref: AouhQQxLZK

**Comment by tuxRamon** [comment]
You'll need to change your hostname /url in the deployment.properties file, to match how you're accessing the service:
server.urls.prefix=

Then restart the RSpace container. See also, the table under the "Installing RSpace on Docker" section in the readme.

**Comment by Tarydium** [comment]
Thank you @tuxRamon.
It was my fault. I set the correct URL but the wrong port (8080 but changed the composer to 8095:8080), now with http://192.168.1.10:8095 it works.
